# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Day1_Animation' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Day1_Animation
pod 'pop'
end
